on:
  push:
    tags:
      - '*'

jobs:
  push-terraform-module-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
<<<<<<< Updated upstream
=======
      - name: Export LATEST_TAG
        run: |
          echo "LATEST_TAG=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV

>>>>>>> Stashed changes
      - uses: ministryofjustice/cloud-platform-environments/cmd/push-terraform-module-version@main
        env:
          API_URL: ${{ vars.TERRAFORM_MODULE_VERSIONS_API_URL }}
          API_KEY: ${{ secrets.TERRAFORM_MODULE_VERSIONS_API_KEY }}
          REPO_NAME: ${{ github.event.repository.name }}
          UPDATED_MODULE_VERSION: ${{ github.ref_name }}
